version: 2.1

orbs:
    node: circleci/node@5.1.0

jobs:
    build-and-test:
        docker:
            - image: cimg/node:12.16
        parallelism: 5
        steps:
            - checkout
            - node/install-packages:
                pkg-manager: yarn      
            - run: mkdir test-results
            - run:
                name: Test application
                command: |
                    TEST=$(circleci tests glob "src/__tests__/*.js" | circleci tests run --command="JEST_JUNIT_ADD_FILE_ATTRIBUTE=true 
                    xargs npx jest --config jest.config.js --runInBand --" --verbose --split-by=timings)
                    yarn test $TEST

            - store_test_results:
                path: test-results

workflows:
    build-and-test:
      jobs:
        - build-and-test