version: 2.1

orbs:
    node: circleci/node@3.0.1

jobs:
    build-and-test:
        docker:
            - image: cimg/node:12.16
        parallelism: 3
        steps:
            - checkout
            - node/install-packages:
                pkg-manager: yarn      
            - run:
                name: Test application
                command: |
                    mkdir test-results
                    TEST_FILES=$(circleci tests glob "src/__tests__/*.js")
                    echo "$TEST_FILES" | circleci tests run --command="xargs -o junit_family=legacy 
                    --junitxml=test-results/junit.xml" --verbose --split-by=timings 
            - store_test_results:
                path: test-results

workflows:
    build-and-test:
      jobs:
        - build-and-test
