version: 2.1

orbs:
    node: circleci/node@3.0.1

jobs:
    build-and-test:
        docker:
            - image: cimg/node:12.16
        parallelism: 3
        steps:
            - checkout
            - run:
                name: Install JUnit coverage reporter
                command: yarn add --dev jest-junit
            - run:
                command: |
                    npx jest --listTests | circleci tests run --command=“JEST_JUNIT_ADD_FILE_ATTRIBUTE=true xargs npx jest --config jest.config.js --runInBand --” --verbose --split-by=timings
                environment:
                  JEST_JUNIT_OUTPUT_DIR: ./reports/
            - store_test_results:
                path: ./reports/

workflows:
    build-and-test:
      jobs:
        - build-and-test
